// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZdzXcBVfMDD9eVYd1zu66eAHLhsTAdaw',
    appId: '1:691274134082:web:c7c6072555d5636d2bb3db',
    messagingSenderId: '691274134082',
    projectId: 'registrationapp-c8f31',
    authDomain: 'registrationapp-c8f31.firebaseapp.com',
    storageBucket: 'registrationapp-c8f31.firebasestorage.app',
    measurementId: 'G-261D3PNX7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC70KnR2hemVlPkxGZAezOQmErDGrnfcLk',
    appId: '1:691274134082:android:a2f60d5e7fac364e2bb3db',
    messagingSenderId: '691274134082',
    projectId: 'registrationapp-c8f31',
    storageBucket: 'registrationapp-c8f31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtUE40CmOIsgfeCwiD62NYrn3pfO8TCSo',
    appId: '1:691274134082:ios:0762e2e5d00c4f392bb3db',
    messagingSenderId: '691274134082',
    projectId: 'registrationapp-c8f31',
    storageBucket: 'registrationapp-c8f31.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtUE40CmOIsgfeCwiD62NYrn3pfO8TCSo',
    appId: '1:691274134082:ios:0762e2e5d00c4f392bb3db',
    messagingSenderId: '691274134082',
    projectId: 'registrationapp-c8f31',
    storageBucket: 'registrationapp-c8f31.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZdzXcBVfMDD9eVYd1zu66eAHLhsTAdaw',
    appId: '1:691274134082:web:979c19ddbce845e62bb3db',
    messagingSenderId: '691274134082',
    projectId: 'registrationapp-c8f31',
    authDomain: 'registrationapp-c8f31.firebaseapp.com',
    storageBucket: 'registrationapp-c8f31.firebasestorage.app',
    measurementId: 'G-WD9B183ZN6',
  );
}
